@echo off
REM Remove directories
rd /s /q ".\MikasBalatro"
rd /s /q ".\Balatro-Preview"
rd /s /q ".\CardBackInjection"
rd /s /q ".\Balatro_CollectionFix"
rd /s /q ".\BlindCollectionPatch"
rd /s /q ".\MystJokers"
rd /s /q ".\MystBlinds"
rd /s /q ".\Better-Mouse-And-Gamepad"
rd /s /q ".\GreenSeal"
rd /s /q ".\JankJonklers"
rd /s /q ".\JellyMod"
rd /s /q ".\Jimbos-Histories"
rd /s /q ".\LushMod"
REM rd /s /q ".\MoreFluff"
rd /s /q ".\multi-jokers"
rd /s /q ".\5_legendary_challenges"
rd /s /q ".\Betmma_Jokers"
rd /s /q ".\SilverSeal"
rd /s /q ".\Steamo"
rd /s /q ".\Balatro---Themed-Jokers"
rd /s /q ".\SylvieSilly"
rd /s /q ".\FederAPI-Balatro"

